ruby '2.1.5'
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'eco'
gem 'useragent'
gem 'erubis'
gem 'sprockets'
gem 'sprockets-commonjs'
gem 'uglifier'
gem 'coffee-script'
gem 'stylus'
