ruby '1.9.3'
source "https://rubygems.org"
ruby '2.0.0'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'unicorn'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'eco'
gem 'useragent'
gem 'erubis'
gem 'sprockets'
gem 'sprockets-commonjs'
gem 'uglifier'
gem 'coffee-script'
gem 'stylus'
